typography_spectrum: 0.49148
color:
  brandColors:
    - '#000000'
    - '#ffd500'
    - '#ff2900'
    - '#008e40'
    - '#ffffff'
  brandStrength: 0.625
  lightness: 0.5625
  saturation: 0.5625
  rhythmicContrast: 0
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 1
analytics:
  google: null
  facebook: null
  twitter: null
name: Radiowave 96.7FM
cta:
  domain: null
  bucket: null
  version: null
favicon: null
title: 'Radiowave 96.7FM '
description: 'Namibia''s #1 Hit Music Station'
purpose: []
