name: Radiowave 96.7FM
favicon: null
layout_spectrum: 0
typography_spectrum: 0.8009321277495474
title: 'Radiowave 96.7FM '
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#ffd500'
    - '#ff2900'
    - '#008e40'
    - '#ffffff'
  brandStrength: 0.625
  lightness: 0.5625
  saturation: 0.5625
  rhythmicContrast: 0
purpose: []
