name: Radiowave 96.7FM
favicon: null
layout_spectrum: 0.72667
typography_spectrum: 0.8009321277495474
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#ffd500'
    - '#ff2900'
    - '#008e40'
    - '#ffffff'
  brandStrength: 0.7185049096588045
  lightness: 0.6058735367842019
  saturation: 0.9522415953688323
  rhythmicContrast: 0.05369900958612561
purpose: []
